Algoritmo "Quadrado"
//Faça um programa que calcula a área de um quadrado.
//em seguida mostre o dobro desta área para o usuário.

Var

   area, dobro, quadrado: real


Inicio
      escreva("Digite a area do quadrado: ")
      leia(area)
      
      quadrado <- area * area
      dobro <- quadrado * 2
      
      
      escreval("Dobro área do quadrado: ",dobro)
      
      


Fimalgoritmo