Algoritmo "teste 4"

Var
     a: real
     b: inteiro


Inicio
      a <- 5.0
      b <- Int(a)
      escreva(b)

       // não posso atribuir um valor de uma variavel que é
       // real para uma variavel que é inteira, pq eu perderia informação
       // dessa maneira se usa o int para informar ao interpretador que eu
       // não me importo com uma possivel perda de informação.
       // INT recebe somente a parte inteira da variavel a

Fimalgoritmo