Algoritmo "NOTAS_ENQUANTO"

Var
  nota: real


Inicio

      escreva("Digite uma nota ")
      leia(nota)
      
      enquanto (nota <0) ou (nota >10) faca
      escreval("ERRO! nota invalida digite novamente")
      leia(nota)
      fimenquanto
      
      se (nota >=7) entao
      escreva("Aluno APROVADO ")
      
      senao
      escreval("Aluno REPROVADO")
      fimse



Fimalgoritmo