Algoritmo "SomaTodosNumerosDigitados_Enquanto"
//Escrever um programa de computador que leia 10 números inteiros e,
// ao final, apresente a soma de todos os números lidos.
Var

   n1, soma, i: inteiro


Inicio
     i<- 0
     soma <- 0
     
     enquanto i < 10 faca
     escreva("Digite um numero: ")
     leia(n1)
     soma <- soma + n1
     i<- i +1
     fimenquanto

     escreva("A soma dos numeros informados = ",soma)

Fimalgoritmo