Algoritmo "testeImparEpar_Estruturas_Repetitiva"


Var
   i: inteiro


Inicio
.
      i <- 1
      
        enquanto (i <=15 ) faca

                 se i % 2 <> 0 entao // numero impar
                 escreval(i)
                 fimse
                 i <- i + 1
                 
                  //se i % 2 = 0 entao numero par
                 //escreval(i)
                 //fimse
                 //i <- i + 1
                 fimenquanto


Fimalgoritmo