Algoritmo "Teste_Soma_Enquanto"
// teste de soma de numeros sozinha para testar meus conhecimentos

Var
   num, soma, i: inteiro


Inicio
      soma <- 0
      i <- 0
      
      escreva("Digite um numero: ")
      leia(num)
      
      enquanto num <> 0 faca
      soma <- soma + num
      i <- i + 1
      escreval("Digite outro numero para somar: ")
      leia(num)
      fimenquanto
      
      escreval("SOMA = ",soma)


Fimalgoritmo